#!/bin/bash

#if (( $((RANDOM%3+1)) == "1" ))
if [ $((RANDOM%3+1)) -eq 1 ]
then base64 /dev/urandom | head -c 500 > file.txt 

elif [ $((RANDOM%3+1)) -eq 2 ]
#elif (( $((RANDOM%3+1)) == "2" )) 
then convert -size 100x100 xc: +noise Random noise.png

elif [ $((RANDOM%3+1)) -eq 3 ]
#elif (( $((RANDOM%3+1)) == "3" ))
then ffmpeg -f lavfi -i "sine=frequency=1000:duration=5" out.wav  

fi

