#!/bin/bash

# Definir la ruta al directorio de entrada y al directorio de descarga
input_dir="../tmp/outputs/descarga"
output_dir="../tmp/outputs/clasificador"

# Crear el directorio de salida y los subdirectorios necesarios
mkdir -p "$output_dir/empty"
mkdir -p "$output_dir/txt"
mkdir -p "$output_dir/snd"
mkdir -p "$output_dir/img"

# Función para clasificar un archivo
classify_file() {
    filename="$1"

    if file -b --mime "$filename" | grep -q "text"; then
        category="txt"
    elif file -b --mime "$filename" | grep -q "audio"; then
        category="snd"
    elif file -b --mime "$filename" | grep -q "image"; then
        category="img"
    elif [ -s "$filename" ]; then
        # Si no se reconoce el tipo, pero el archivo no está vacío, moverlo a otro directorio
        category="otros"
    else
        # Si el archivo está vacío, moverlo a la carpeta "empty"
        category="empty"
    fi

    target_dir="$output_dir/$category"
    mkdir -p "$target_dir"
    mv "$filename" "$target_dir/"
}

# Comprobar si existen archivos en el directorio de entrada
if [ -z "$(ls -A "$input_dir")" ]; then
    echo "No hay archivos para procesar en el directorio de entrada."
else
    # Procesar archivos en el directorio de entrada
    for file in "$input_dir"/*; do
        if [ -f "$file" ]; then
            classify_file "$file"
        fi
    done
fi
echo "Listo."
# Contar y mostrar cuántos archivos vacíos se movieron
empty_count=$(find "$output_dir/empty" -type f | wc -l)
echo "Se movieron $empty_count archivos vacíos a $output_dir/empty."
