#!/bin/bash

while true; do
    clear
    echo "Menú Principal"
    echo "1. Descargar, clasificar y comprimir archivos"
    echo "2. Monitorear sistema"
    echo "3. Salir"

    read -p "Elija una opción (1/2/3): " choice
    
    dir_rastreo=$(dirname "$0")

    case $choice in
        1)
            # Llamar a la función de descarga de archivos
            bash "$dir_rastreo/descarga"
	    bash "$dir_rastreo/clasificador"
	    bash "$dir_rastreo/compressor"
            ;;
        2)
            # Llamar a la función de monitoreo del sistema
            bash "$dir_rastreo/monitoreo"
            ;;
        3)
            echo "Saliendo..."
            exit
            ;;
        *)
            echo "Opción inválida. Intente nuevamente."
            ;;
    esac

    read -p "Presione Enter para continuar..."
done
