#!/bin/bash

script_dir="$(dirname "$0")"
output_dir="${script_dir}/outputs"


for file in "${script_dir}"/*; do
    if [[ -f "$file" ]]; then
        file_ext="${file##*.}"
        
        if [[ "$file_ext" == "txt" ]]; then
            mv "$file" "${output_dir}/txt/"
        elif [[ "$file_ext" == "wav" ]]; then
            mv "$file" "${output_dir}/snd/"
        elif [[ "$file_ext" == "png" || "$file_ext" == "jpg" || "$file_ext" == "jpeg" || "$file_ext" == "gif" ]]; then
            mv "$file" "${output_dir}/img/"
        fi
    fi
done

