#!/bin/bash

script_dir="$(dirname "$0")"
output_dir="/home/matias/edp-2023-ci/estudiantes/santucho-matias/tp1/generador/outputs_generador"
txt_count=0
snd_count=0
img_count=0

for file in ${output_dir} *; do
    if [[ -f "$file" ]]; then
        file_type=$(file -b --mime-type "$file")
	echo $file_type

        case "$file_type" in
            "text/plain")
                txt_count=$((txt_count+1)) 
                mv "$file" "txt${txt_count}"
                mv "txt${txt_count}" "/home/matias/edp-2023-ci/estudiantes/santucho-matias/tp1/usuario/outputs_clasificador/txt/"
                ;;
            "audio/x-wav")
                snd_count=$((snd_count+1))
                mv "$file" "wav${snd_count+1}"
                mv "wav${snd_count+1}" "/home/matias/edp-2023-ci/estudiantes/santucho-matias/tp1/usuario/outputs_clasificador/snd/"
                ;;
            "image/png" | "image/jpeg")
                img_count=$((img_count+1))
                mv "$file" "png${img_count}"
                mv "png${img_count}" "/home/matias/edp-2023-ci/estudiantes/santucho-matias/tp1/usuario/outputs_clasificador/img"
                ;;
        esac
    fi
done
