#!/bin/bash
rm -rf outputs_clasificador/*

mkdir -p outputs_clasificador/txt
mkdir -p outputs_clasificador/img
mkdir -p outputs_clasificador/snd


cont_audio=1
cont_imagen=1
cont_texto=1

cd descargas

for file in *; do
    tipo_archivo=$(file "$file")

    if echo "$tipo_archivo" | grep -qE "RIFF|audio"; then
        mv "$file" "archivo-sonido${cont_audio}.wav"
        mv "archivo-sonido${cont_audio}.wav" "../outputs_clasificador/snd"
        cont_audio=$((cont_audio + 1))
    elif echo "$tipo_archivo" | grep -qE "ASCII"; then
        mv "$file" "archivo-texto${cont_texto}.txt"
        mv "archivo-texto${cont_texto}.txt" "../outputs_clasificador/txt"
        cont_texto=$((cont_texto + 1))
    elif echo "$tipo_archivo" | grep -qE "JPEG"; then
        mv "$file" "archivo-imagen${cont_imagen}.png"
        mv "archivo-imagen${cont_imagen}.png" "../outputs_clasificador/img"
        cont_imagen=$((cont_imagen + 1))

    fi
