#!/bin/bash

FECHA=$(date +"%d_%m_%Y_%H_%M_%S")
NOMBRE_ARCHIVO="./outputs/outputs_clasificador_$FECHA.tar"

tar -cvf "$NOMBRE_ARCHIVO" -C "$(dirname "$0")" outputs_clasificador/

echo "Archivo comprimido creado"
